version: "3.7"

services:

  flask:
    image: shantanoodesai/nimble-iot-blockchain-api:1.5
    environment:
      - APP_CONFIG=production.cfg
    volumes:
      ./production.cfg:/iotblockchainApp/nimble_iot_bc/production.cfg
    restart: always
    ports:
      - "5000:5000"