version: "3.7"

services:

  flask:
    image: nimble-iot-blockchain-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_CONFIG=testing.cfg
    restart: always
    ports:
      - "5000:5000"